stages:             # these stages (jobs) forms the CICD pipeline
  - mavenbuild      # this is a JOB to build your Springboot application
  - maventest       # this is a JOB to run tests in your Springboot application (it's okay you don't have any test for now)
  - mavendeploy     # this is a JOB to deploy your Springboot application on your server
  - androidBuild
  - androidTest

maven-build:            
  stage: mavenbuild     # one of the stages listed above
  tags:                 # to specify which runner to execute this job
    - springboot_tag    # change to your runner's tag
  script:               # what to execute for this job
    - cd Backend/4_sh_2_backend_project        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn package       # maven package
  artifacts:            # where to output the packaged jar file, change 'Backend' to to where you have the pom.xml
    paths:
    - Backend/4_sh_2_backend_project/target/*.jar
  only:
    refs:
      - main           # only to trigger the pipeline when changes are pushed to 'main'
    changes:
      - Backend/**/*       # more specifically - only when changes are made inside the 'Backend' folder

maven-test:             
  stage: maventest     # one of the stages listed above
  tags:
     - springboot_tag   # change to your runner's tag
  script:
     - cd Backend/4_sh_2_backend_project       # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
     - mvn test         # maven test
  only:
    refs:
      - main          # only to trigger the pipeline when changes are pushed to 'main'
    changes:
      - Backend/**/*       # more specifically - only when changes are made inside the 'Backend' folder

android-build: #this is another job
  image: afirefly/android-ci:java17      		# this is a directive to DOCKER
  stage: androidBuild
  tags:
   - frontend_tag         					#this is LINK to the docker runner on the remote-server        
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/PocketDeck/gradlew			#change directory to where you have ‘gradlew’ in your android directory
  script:
    - cd Frontend/PocketDeck					#change directory to where you have your android application
    - ./gradlew assemble
  only:
    refs:
      - main
    changes:
      - Frontend/**/*

android-test:
  image: afirefly/android-ci:java17      		# this is a directive to DOCKER
  stage: androidTest
  tags:
   - frontend_tag         					#this is LINK to the docker runner on the remote-server        
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/PocketDeck/gradlew			#change directory to where you have ‘gradlew’ in your android directory
  script:
    - cd Frontend/PocketDeck					#change directory to where you have your android application
    - ./gradlew assemble
  only:
    refs:
      - main
    changes:
      - Frontend/**/*

auto-deploy:
  stage: mavendeploy  #do make a stage with same name!
  tags:
   - springboot_tag   #do have a runner with same tag
  script:
    - cd Backend/4_sh_2_backend_project
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    refs:
      - main # only triggers pipelin when changes are pushed to "main"
    changes:
    - Backend/**/*
