/**
 * @author Mack Quinn
 */

package com.example.pocketdeck;

import android.content.Intent;
import android.content.SharedPreferences;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.CompoundButton;
import android.widget.SeekBar;
import android.widget.Switch;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

public class Settings extends AppCompatActivity {

    private Button backButton;
    private Switch effectsSwitch;
    private Switch musicSwitch;
    private SeekBar volumeControl;

    //private static MediaPlayer music;

    /**
     *
     * @param savedInstanceState If the activity is being re-initialized after
     *     previously being shut down then this Bundle contains the data it most
     *     recently supplied in {@link #onSaveInstanceState}.  <b><i>Note: Otherwise it is null.</i></b>
     *
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_settings);
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });

        backButton = findViewById(R.id.backButton);
        effectsSwitch = findViewById(R.id.soundEffectsSwitch);
        musicSwitch = findViewById(R.id.musicSwitch);
        volumeControl = findViewById(R.id.volumeBar);

        //set the colume bar to max at 100 and start at 75 as default
        volumeControl.setMax(100);
        volumeControl.setProgress(75);
        //create the music player. music is stored in raw on android studio

        //access the users saved settings from preferences
        SharedPreferences preferences = getSharedPreferences("userPreferences", MODE_PRIVATE);
        musicSwitch.setChecked(preferences.getBoolean("musicOn", true));
        volumeControl.setProgress(preferences.getInt("volume", 75));

        //switch listener so it can turn on and off with the settings button
        musicSwitch.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            /**
             *
             * @param buttonView The compound button view whose state has changed.
             * @param isChecked  The new checked state of buttonView.
             */
            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                //if swtich is on then play. if no tthen turn off
                //this check is now done in MusicPlayer.java
                preferences.edit().putBoolean("musicOn", isChecked).apply();
                MusicPlayer.startMusic(Settings.this);
                MusicPlayer.pauseMusic();
            }
        });

        //lisitener for the volume control slider

        volumeControl.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
            @Override
            public void onProgressChanged(SeekBar volumeBar, int userVolume, boolean fromUser) {
                preferences.edit().putInt("volume", userVolume).apply();
                MusicPlayer.Volume(userVolume);
            }

            @Override
            public void onStartTrackingTouch(SeekBar seekBar) {
                //i dont think we need this. for when the user touches the slider. It autogenerated
            }

            @Override
            public void onStopTrackingTouch(SeekBar seekBar) {
                // this is the same as start but is for when you release the slider.
                // dont think we need it. It autogenerated
            }
        });

        backButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent i = new Intent(Settings.this, MainActivity.class);
                startActivity(i);
            }
        });
    }
    @Override
    protected void onResume() {
        super.onResume();
        MusicPlayer.musicPref(this);
    }
}